openapi: 3.0.0
info:
  title: GptAPI
  description: |
    Proporciona una REST API para usar el servicio de ChatGPT
  version: 0.0.1
tags:
  - name: ChatGPT-3.5
paths:
  /chat:
    post:
      tags:
        - ChatGPT-3.5
      summary: Interactua con el chat ChatGPT-3.5
      description: Proporciona un servicio eficiente y potente para interactuar con el modelo GPT-3.5
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GptBody"            
      responses:
        "200":
          description: Respuesta del modelo GPT
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer: 
                    type: string
                    example: El creador de GPT es OpenAI
components:
  schemas:
    GptBody:
      properties:
        prompt_system:
          type: string
          example: Actua como un chatbot y responde la siguiente pregunta
        prompt_user:
          type: string
          example: Quien es el creador de Chat GPT
        temperature: 
          type: number
          example: 0.4